name: Mulesoft - Deploy
on:
  workflow_call:
   inputs:
     Version:
          type: string  
     Environment:
          type: string  
jobs:
   DeploytoMule:  
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Version Number
          run: echo "REL_VERSION = ${{ inputs.Version }}"
          
        - name: Download Artifact
          if: ${{ (inputs.Environment == 'dev') || (inputs.Environment == 'test')  }}
          run: echo "Download Artifact"
          
        - name: Download Artifact
          if: ${{ inputs.Environment == 'stg' }}
          run: echo "Download Artifact"
              
        - name: Deploy to Cloudhub        
          run: echo "Deploy to Cloudhub"
