name:  Parent_workflow_Stg_Deployment_POC
on:
  workflow_dispatch:
   inputs: 
       version:
          description: 'version'
          required: true
          type: string  
          
permissions:
    contents: write
    packages: write
    actions: write
    id-token: write
    
jobs: 
  Parent-call:
      runs-on: ubuntu-latest
      steps:            
        - name: Repository dispatch to Service1-Mule    
          run: |
               curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service1-Mule/dispatches \
                -d '{"event_type":"Service1-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'
                
        - name: Repository dispatch to Service2-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service2-Mule/dispatches \
                -d '{"event_type":"Service2-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service3-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service3-Mule/dispatches \
                -d '{"event_type":"Service3-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}' 

        - name: Repository dispatch to Service-common
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/ServiceCommon-Mule/dispatches \
                -d '{"event_type":"ServiceCommon-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'        
                
        - name: Repository dispatch to Service4-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service4-Mule/dispatches \
                -d '{"event_type":"Service4-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service5-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service5-Mule/dispatches \
                -d '{"event_type":"Service5-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service6-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service6-Mule/dispatches \
                -d '{"event_type":"Service6-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service7-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service7-Mule/dispatches \
                -d '{"event_type":"Service7-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service8-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service8-Mule/dispatches \
                -d '{"event_type":"Service8-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service9-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service9-Mule/dispatches \
                -d '{"event_type":"Service9-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service10-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service10-Mule/dispatches \
                -d '{"event_type":"Service10-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service11-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service11-Mule/dispatches \
                -d '{"event_type":"Service11-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service12-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service12-Mule/dispatches \
                -d '{"event_type":"Service12-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service13-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service13-Mule/dispatches \
                -d '{"event_type":"Service13-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service14-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service14-Mule/dispatches \
                -d '{"event_type":"Service14-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service15-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service15-Mule/dispatches \
                -d '{"event_type":"Service15-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service16-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service16-Mule/dispatches \
                -d '{"event_type":"Service16-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service17-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service17-Mule/dispatches \
                -d '{"event_type":"Service17-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service18-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service18-Mule/dispatches \
                -d '{"event_type":"Service18-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service19-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service19-Mule/dispatches \
                -d '{"event_type":"Service19-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service20-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service20-Mule/dispatches \
                -d '{"event_type":"Service20-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

        - name: Repository dispatch to Service21-Mule
          run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/Service21-Mule/dispatches \
                -d '{"event_type":"Service21-Mule","client_payload":{"Version":"${{ inputs.version }}","Repo":"${{ github.repository }}"}}'

