name:  Parent_workflow_Stg_Deployment_POC
on:
  workflow_dispatch:
   inputs: 
       version:
          description: 'version'
          required: true
          type: string  
          
permissions:
    contents: write
    packages: write
    actions: write
    id-token: write
    
jobs: 
  Parent-call:
      runs-on: ubuntu-latest
      steps:            
        - name: Repository dispatch to Service1-Mule    
          run: |
               curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/neworgshiyam/DevOpsCommon-Mule/dispatches \
                -d '{"event_type":"Service1-Mule","client_payload":{"Version":${{ inputs.version }},"Repo":${{ github.repository }} }}'
                
        # - name: Repository dispatch to Service2-Mule
        #   run: |
        #        curl -L \
        #         -X POST \
        #         -H "Accept: application/vnd.github+json" \
        #         -H "Authorization: Bearer ${{ secrets.REPOSITORY_DISPTACH }}" \
        #         -H "X-GitHub-Api-Version: 2022-11-28" \
        #         https://api.github.com/repos/OWNER/REPO/dispatches \
        #         -d '{"event_type":"Service2-Mule","client_payload":{"Version":{{ inputs.version }}}}'
          
